name: CI Master Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Fetch our code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache premake
        id: premake-cache
        uses: actions/cache@v3.0.11
        with:
          path: .premake
          key: cache-premake
        
      - name: Setup Premake
        if: steps.premake-cache.outputs.cache-hit != 'true'
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta2"
          
      - name: Run Premake
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: .premake/premake5.exe vs2022
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Build solution
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Debug EpEngine.sln
